### ISSUE TITLE
boot8266 on power-up goes into OTA mode

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/yaota8266#1]
Unconditionally, or at least most of the time, even if firmware image is good. Apparently, an OTA button press on boot-up is mis-detected on the initial power-up. This doesn't happen with hardware reset, etc.

**Comment by pfalcon** [comment]
@dpgeorge: FYI.

**Comment by dpgeorge** [comment]
I'll have to test it myself.  Maybe it needs a short delay for the GPIO to settle down before checking them?

**Comment by pfalcon** [comment]
Maybe and that's the obvious way to deal with it. But see e.g. #3. This also may be an artifact of boards which have GPIO0 connected to serial signalling (i.e. not be an internal issue of esp8266, but rather of external plumbing), would be helpful to understand if that's the case.

**Comment by dpgeorge** [comment]
My board has GPIO0 connected to an LED and it still has the issue.  I tried adding a 1sec delay before checking the GPIO but that didn't help.

But after playing around with it it seems like it is related to UART0 being connected to GPIO1 and GPIO3.  My board boots into the application upon power up but only if I don't connect to the UART0 serial during the 3 second window.  So I then tried masking off the GPIO bits that are checked for changes, to check only GPIO0, 2, 4 and 5.  But that didn't seem to fix it.

Do we really want to check all of the GPIO for change during boot?  What about those IO connected to SPI flash, shouldn't they at least be masked?

**Comment by pfalcon** [comment]
> Do we really want to check all of the GPIO for change during boot? What about those IO connected to SPI flash, shouldn't they at least be masked?

Sure, we want to have the mask, and even runtime-configurable mask (like, a user should be able to set it for a particular device one has). I'll add at least just a mask when I get a chance.

But worst-case, we have some unstable GPIO reading on power-up, and the situation is still unclear with comments like:

>  But that didn't seem to fix it.

So, will likely need to add extensive debug logging to be able to figure it out.

**Comment by pfalcon** [comment]
Ok, gpio_mask param added in https://github.com/pfalcon/yaota8266/commit/25a031c005510337744acd344d03fad52021e69a, both compile-time, and with forward-looking provision to update it post-deployment. Default value flters out UART and FlashROM pins. I didn't actually tested the issue in the ticket title yet with these changes.

**Comment by pfalcon** [comment]
Confirmed that with current default settings, a device boots into the main app on power-up.
