### ISSUE TITLE
ota-server is missing config.h file

### ISSUE THREAD

**Issue by dpgeorge** [pfalcon/yaota8266#4]
It looks like this file should define OTA_START and MOD.

**Comment by pfalcon** [comment]
Right, expectedly, it should be generated by a user, but I pushed an example in https://github.com/pfalcon/yaota8266/commit/005b80c21ef0eb1a8e9050bad8d8da05b6385e15 (I mentioned that the repo is rebased, right, so link may become dangling later).

How to make up a MOD binstring? Well, routines in https://github.com/pfalcon/yaota8266/blob/master/ota-client/rsa_sign.py (also just added) can definitely print it https://github.com/pfalcon/yaota8266/blob/master/ota-client/rsa_sign.py

(All needs polishing up.)

**Comment by pfalcon** [comment]
config.h.example is now moved to the top-level dir, and shared by both boot8266 and ota-server. I guess this ticket now can be closed.
