### ISSUE TITLE
"AES encryption" is broken

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/yaota8266#6]
An expected example of brokenness of "3am crypto". "AES encryption" as implemented by ota-server/ota-client is broken. AES packet key is RSA-signed, with RSA-signing being a kind of encryption. The problem, it is "encrypted" to be "decrypted" with a public key, which everyone has, so anyone can recover AES key for a packet.

To be able to use "session keys", there should be a proper key exchange, which requires 2 pairs of keys, assignment of a private key to each device, etc. complications. The whole idea of ota-server was to make something simpler than TLS, not to reimplement it.

Now the question what to do: a) leave AES in place, as a kind of "data whitening" (so someone couldn't see data plain-text in the air, even though it can be recovered with additional processing); b) remove AES altogether.

At this point, b) is apparently more complicated ;-). But given changes needed for #5, maybe removing AES to not cause confusion is a logical step.

**Comment by dpgeorge** [comment]
Leaving AES as-is might lead to some people believing that the OTA process is secure, when it fact it's not.  So I'd suggest going the route of (b), and adding `#if 0` to simply disable AES, so it can be easily added back later.

**Comment by pfalcon** [comment]
Ok, AES is commented out and docs updated to not mention it.
